- name: print names using loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "Hello, {{ item }}" # item is reserved keyword here
    loop:
     - suresh 
     - kiran
     - sudharkar
     - sirisha
     - anu