- name: install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      state: started
      enabled: yes