- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    # ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"

  - name: command module ls output
    # ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.command: "ls -ltr"
    register: command_output

  - name: print the outcome
    ansible.builtin.debug:
      msg: "{{ command_output }}"


       