- name: shell vs command
  hosts: frontend
  tasks:
  - name: redirect ls output to a file
    # ansible.builtin.command: "ls -ltr > /tmp/output.txt"
    ansible.builtin.shell: "ls -ltr > /tmp/output.txt"
    register: command_result

  - name: proint the outcome
    ansible.builtin.debug:
      msg: "{{ command_result }}"